name: Build & Release

on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    permissions:
      contents: write # crear el release y subir el instalador
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar app
        run: npm run build

      - name: Empaquetar y publicar (.exe + latest.yml)
        run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write # crear el release y subir el AppImage
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar app
        run: npm run build

      - name: Empaquetar y publicar (.AppImage + latest-linux.yml)
        run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
